name: Release

on:
  release:
    types: [published]

jobs:
  native-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Excluding JVM and JS targets
        run: echo excludeTargets = jvm,js >> gradle.properties
        shell: bash
      - name: Assemble
        run: |
          ./gradlew :kodein-di:assemble
          ./gradlew :kodein-di-conf:assemble
        shell: bash
      - name: Test
        run: |
          ./gradlew :kodein-di:check
          ./gradlew :kodein-di-conf:check
        shell: bash
      - name: Upload to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: |
          ./gradlew :kodein-di:bintrayUpload
          ./gradlew :kodein-di-conf:bintrayUpload
        shell: bash
  jvm-and-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Excluding Native targets
        run: echo "excludeTargets = native" >> gradle.properties
      - name: Assemble
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew check
      - name: Upload to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: ./gradlew bintrayUpload