# This is a basic workflow to help you get started with Actions

name: snapshot-linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kodein-di-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker://romainbsl/kmp-native:1.3.71
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Disable JVM and JS
        run: echo excludeTargets = jvm,js >> gradle.properties
      # Runs a single command using the runners shell
      - name: assemble
        run: ./gradlew :kodein-di:assemble
      - name: test
        run: ./gradlew :kodein-di:check
      - name: deploy
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: ./gradlew :kodein-di:bintrayUpload -PsnapshotNumber=$GITHUB_RUN_NUMBER
  kodein-di-conf-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker://romainbsl/kmp-native:1.3.71
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Disable JVM and JS
        run: echo excludeTargets = jvm,js >> gradle.properties
      # Runs a single command using the runners shell
      - name: assemble
        run: ./gradlew :kodein-di-conf:assemble
      - name: test
        run: ./gradlew :kodein-di-conf:check
      - name: deploy
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: ./gradlew :kodein-di-conf:bintrayUpload -PsnapshotNumber=$GITHUB_RUN_NUMBER
  jvm-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Disable Native
        run: echo "excludeTargets = native" >> gradle.properties
      # Runs a single command using the runners shell
      - name: assemble
        run: ./gradlew assemble
      - name: test
        run: ./gradlew check
      - name: deploy
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: ./gradlew bintrayUpload -PsnapshotNumber=$GITHUB_RUN_NUMBER
  kodein-di-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Native Only
        run: echo excludeTargets = jvm,js >> gradle.properties
        shell: bash
      - name: assemble
        run: ./gradlew :kodein-di:assemble --stacktrace
        shell: bash
      - name: test
        run: ./gradlew :kodein-di:check
        shell: bash
      - name: deploy
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: ./gradlew :kodein-di:bintrayUpload -PsnapshotNumber=$GITHUB_RUN_NUMBER
  kodein-di-conf-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Native Only
        run: echo excludeTargets = jvm,js >> gradle.properties
        shell: bash
      - name: assemble
        run: ./gradlew :kodein-di-conf:assemble
        shell: bash
      - name: test
        run: ./gradlew :kodein-di-conf:check
        shell: bash
      - name: deploy
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: ./gradlew :kodein-di-conf:bintrayUpload -PsnapshotNumber=$GITHUB_RUN_NUMBER
        shell: bash