name: Build and deploy snapshots

on:
  push:
    branches:
      - master
      - 'snapshot/[0-9]+.[0-9]+'

jobs:
  native-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Excluding JVM and JS targets
        run: echo excludeTargets = jvm,js >> gradle.properties
        shell: bash
      - name: assemble
        run: |
          ./gradlew :kodein-di:assemble
          ./gradlew :kodein-di-conf:assemble
        shell: bash
      - name: test
        run: |
          ./gradlew :kodein-di:check
          ./gradlew :kodein-di-conf:check
        shell: bash
      - name: deploy
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: |
          ./gradlew :kodein-di:bintrayUpload -PsnapshotNumber=${{ github.run_number }}
          ./gradlew :kodein-di-conf:bintrayUpload -PsnapshotNumber=${{ github.run_number }}
        shell: bash
  jvm-js:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Excluding Native targets
        run: echo "excludeTargets = native" >> gradle.properties
      # Runs a single command using the runners shell
      - name: assemble
        run: ./gradlew assemble
      - name: test
        run: ./gradlew check
      - name: deploy
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: ./gradlew bintrayUpload -PsnapshotNumber=${{ github.run_number }}